### PR TITLE
update repo and main developers

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

Updated repos and added main developer

Would the following people be able to check the repos and confirm they are happy to be `main developer`. There are perhaps some we can move around. 

@JackKelly @jacobbieker @devsjc @braddf @rachel-labri-tipton @zakwatts 

Screenshot 2023-07-04 at 10 13 00
Screenshot 2023-07-04 at 10 13 05
Screenshot 2023-07-04 at 10 13 09

## How Has This Been Tested?

Looked at it locally
- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by jacobbieker** [comment]
I'm happy with the ones I'm on! Depending if @JackKelly  doesn't want the NWP one, I can also take that one, as I've been adding more to it recently, for ICON, MeteoFrance, and MetOffice. 

We might want to deprecate/archive nowcasting_dataloader,dataset,satflow, and predict_pv_yield repos, as we don't really do development on those anymore, and the models/datasets are in newer ones. Although that might be for a followup PR.

**Comment by rachel-labri-tipton** [comment]
Looks fine for me!

**Comment by zakwatts** [comment]
Looks good to me!

**Comment by JackKelly** [comment]
Looks good to me! I'm happy for Jacob to take the NWP repo, I don't mind! (although we should perhaps merge that with the operational NWP repo... But no rush, that's a lot of work)

**Pull request merged**
